name: "CI"
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: [ 38, 39 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://releases.nixos.org/nix/nix-2.3.10/install
          extra_nix_config: "system-features = benchmark kvm"
      - name: Run tests on Python${{ matrix.python-version }}
        run: |
          nix-shell --argstr pyVersion ${{ matrix.python-version }} --run \
          "pip install -e . && pip install -r requirements/test.txt && pip install -r requirements/extras/third_party.txt && make test"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: python${{ matrix.python-version }}
          parallel: true
          path-to-lcov:  ./coverage.xml
